import {
  addPersonalTxExFn,
  addTransactionFn,
  createTaskFn,
  deletePersonalTxFn,
  deletePersonalAccountFn,
  deletePersonalBudgetFn,
  deletePersonalCategoryFn,
  deletePersonalCounterpartyFn,
  deletePersonalLoanFn,
  deleteTaskFn,
  deleteTransactionFn,
  setTaskRemarkFn,
  toggleTaskFn,
  updatePersonalTxFn,
  upsertPersonalAccountFn,
  upsertPersonalBudgetFn,
  upsertPersonalCategoryFn,
  upsertPersonalCounterpartyFn,
  upsertPersonalLoanFn,
  createPersonalProfileFn,
  renamePersonalProfileFn,
  deletePersonalProfileFn,
  upsertBusinessAccountFn,
  deleteBusinessAccountFn,
  transferBusinessFundsFn,
} from "@/lib/zt.functions";
import {
  createListFn,
  createTodoFn,
  deleteListFn,
  deleteNoteFn,
  deleteTodoFn,
  togglePinNoteFn,
  toggleTodoFn,
  updateListFn,
  updateTodoFn,
  upsertNoteFn,
} from "@/lib/notebook.functions";
import { registerOfflineRunner } from "@/lib/offline-queue";

export const OFFLINE_OPS = {
  PERSONAL_PROFILE_CREATE: "personal.profile.create",
  PERSONAL_PROFILE_RENAME: "personal.profile.rename",
  PERSONAL_PROFILE_DELETE: "personal.profile.delete",
  PERSONAL_TX_ADD: "personal.tx.add",
  PERSONAL_TX_UPDATE: "personal.tx.update",
  PERSONAL_TX_DELETE: "personal.tx.delete",
  PERSONAL_ACCOUNT_UPSERT: "personal.account.upsert",
  PERSONAL_ACCOUNT_DELETE: "personal.account.delete",
  PERSONAL_CATEGORY_UPSERT: "personal.category.upsert",
  PERSONAL_CATEGORY_DELETE: "personal.category.delete",
  PERSONAL_COUNTERPARTY_UPSERT: "personal.counterparty.upsert",
  PERSONAL_COUNTERPARTY_DELETE: "personal.counterparty.delete",
  PERSONAL_LOAN_UPSERT: "personal.loan.upsert",
  PERSONAL_LOAN_DELETE: "personal.loan.delete",
  PERSONAL_BUDGET_UPSERT: "personal.budget.upsert",
  PERSONAL_BUDGET_DELETE: "personal.budget.delete",
  BUSINESS_TX_ADD: "business.tx.add",
  BUSINESS_TX_DELETE: "business.tx.delete",
  BUSINESS_ACCOUNT_UPSERT: "business.account.upsert",
  BUSINESS_ACCOUNT_DELETE: "business.account.delete",
  BUSINESS_ACCOUNT_TRANSFER: "business.account.transfer",
  TASK_CREATE: "task.create",
  TASK_TOGGLE: "task.toggle",
  TASK_DELETE: "task.delete",
  TASK_REMARK: "task.remark",
  LIST_CREATE: "notebook.list.create",
  LIST_UPDATE: "notebook.list.update",
  LIST_DELETE: "notebook.list.delete",
  NOTE_UPSERT: "notebook.note.upsert",
  NOTE_PIN: "notebook.note.pin",
  NOTE_DELETE: "notebook.note.delete",
  TODO_CREATE: "notebook.todo.create",
  TODO_UPDATE: "notebook.todo.update",
  TODO_TOGGLE: "notebook.todo.toggle",
  TODO_DELETE: "notebook.todo.delete",
} as const;

type CallableServerFn = (options: { data: unknown }) => Promise<unknown>;

function runner(serverFn: unknown) {
  return (data: unknown) => (serverFn as CallableServerFn)({ data });
}

export function registerCoreOfflineRunners() {
  const registrations: Array<[string, unknown]> = [
    [OFFLINE_OPS.PERSONAL_PROFILE_CREATE, createPersonalProfileFn],
    [OFFLINE_OPS.PERSONAL_PROFILE_RENAME, renamePersonalProfileFn],
    [OFFLINE_OPS.PERSONAL_PROFILE_DELETE, deletePersonalProfileFn],
    [OFFLINE_OPS.PERSONAL_TX_ADD, addPersonalTxExFn],
    ["addPersonalTxEx", addPersonalTxExFn],
    [OFFLINE_OPS.PERSONAL_TX_UPDATE, updatePersonalTxFn],
    [OFFLINE_OPS.PERSONAL_TX_DELETE, deletePersonalTxFn],
    [OFFLINE_OPS.PERSONAL_ACCOUNT_UPSERT, upsertPersonalAccountFn],
    [OFFLINE_OPS.PERSONAL_ACCOUNT_DELETE, deletePersonalAccountFn],
    [OFFLINE_OPS.PERSONAL_CATEGORY_UPSERT, upsertPersonalCategoryFn],
    [OFFLINE_OPS.PERSONAL_CATEGORY_DELETE, deletePersonalCategoryFn],
    [OFFLINE_OPS.PERSONAL_COUNTERPARTY_UPSERT, upsertPersonalCounterpartyFn],
    [OFFLINE_OPS.PERSONAL_COUNTERPARTY_DELETE, deletePersonalCounterpartyFn],
    [OFFLINE_OPS.PERSONAL_LOAN_UPSERT, upsertPersonalLoanFn],
    [OFFLINE_OPS.PERSONAL_LOAN_DELETE, deletePersonalLoanFn],
    [OFFLINE_OPS.PERSONAL_BUDGET_UPSERT, upsertPersonalBudgetFn],
    [OFFLINE_OPS.PERSONAL_BUDGET_DELETE, deletePersonalBudgetFn],
    [OFFLINE_OPS.BUSINESS_TX_ADD, addTransactionFn],
    [OFFLINE_OPS.BUSINESS_TX_DELETE, deleteTransactionFn],
    [OFFLINE_OPS.BUSINESS_ACCOUNT_UPSERT, upsertBusinessAccountFn],
    [OFFLINE_OPS.BUSINESS_ACCOUNT_DELETE, deleteBusinessAccountFn],
    [OFFLINE_OPS.BUSINESS_ACCOUNT_TRANSFER, transferBusinessFundsFn],
    [OFFLINE_OPS.TASK_CREATE, createTaskFn],
    [OFFLINE_OPS.TASK_TOGGLE, toggleTaskFn],
    [OFFLINE_OPS.TASK_DELETE, deleteTaskFn],
    [OFFLINE_OPS.TASK_REMARK, setTaskRemarkFn],
    [OFFLINE_OPS.LIST_CREATE, createListFn],
    [OFFLINE_OPS.LIST_UPDATE, updateListFn],
    [OFFLINE_OPS.LIST_DELETE, deleteListFn],
    [OFFLINE_OPS.NOTE_UPSERT, upsertNoteFn],
    [OFFLINE_OPS.NOTE_PIN, togglePinNoteFn],
    [OFFLINE_OPS.NOTE_DELETE, deleteNoteFn],
    [OFFLINE_OPS.TODO_CREATE, createTodoFn],
    [OFFLINE_OPS.TODO_UPDATE, updateTodoFn],
    [OFFLINE_OPS.TODO_TOGGLE, toggleTodoFn],
    [OFFLINE_OPS.TODO_DELETE, deleteTodoFn],
  ];

  const unregister = registrations.map(([key, serverFn]) =>
    registerOfflineRunner(key, runner(serverFn)),
  );
  return () => unregister.forEach((dispose) => dispose());
}
