/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppPersonalRouteImport } from './routes/_app.personal'
import { Route as AppNotebookRouteImport } from './routes/_app.notebook'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppPersonalIndexRouteImport } from './routes/_app.personal.index'
import { Route as AppNotebookIndexRouteImport } from './routes/_app.notebook.index'
import { Route as AppChatIndexRouteImport } from './routes/_app.chat.index'
import { Route as AppPersonalIdRouteImport } from './routes/_app.personal.$id'
import { Route as AppNotebookTodayRouteImport } from './routes/_app.notebook.today'
import { Route as AppMyTasksRouteImport } from './routes/_app.my.tasks'
import { Route as AppChatNewRouteImport } from './routes/_app.chat.new'
import { Route as AppChatConversationIdRouteImport } from './routes/_app.chat.$conversationId'
import { Route as AppBusinessesIdRouteImport } from './routes/_app.businesses.$id'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppNotebookListsIndexRouteImport } from './routes/_app.notebook.lists.index'
import { Route as AppBusinessesIdIndexRouteImport } from './routes/_app.businesses.$id.index'
import { Route as AppNotebookNotesNoteIdRouteImport } from './routes/_app.notebook.notes.$noteId'
import { Route as AppNotebookListsListIdRouteImport } from './routes/_app.notebook.lists.$listId'
import { Route as AppBusinessesIdTasksRouteImport } from './routes/_app.businesses.$id.tasks'
import { Route as AppBusinessesIdProfitRouteImport } from './routes/_app.businesses.$id.profit'
import { Route as AppBusinessesIdPeopleRouteImport } from './routes/_app.businesses.$id.people'
import { Route as AppBusinessesIdMoneyRouteImport } from './routes/_app.businesses.$id.money'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonalRoute = AppPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => AppRoute,
} as any)
const AppNotebookRoute = AppNotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonalIndexRoute = AppPersonalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPersonalRoute,
} as any)
const AppNotebookIndexRoute = AppNotebookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppNotebookRoute,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChatRoute,
} as any)
const AppPersonalIdRoute = AppPersonalIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPersonalRoute,
} as any)
const AppNotebookTodayRoute = AppNotebookTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppNotebookRoute,
} as any)
const AppMyTasksRoute = AppMyTasksRouteImport.update({
  id: '/my/tasks',
  path: '/my/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppChatNewRoute = AppChatNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppChatRoute,
} as any)
const AppChatConversationIdRoute = AppChatConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => AppChatRoute,
} as any)
const AppBusinessesIdRoute = AppBusinessesIdRouteImport.update({
  id: '/businesses/$id',
  path: '/businesses/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppNotebookListsIndexRoute = AppNotebookListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => AppNotebookRoute,
} as any)
const AppBusinessesIdIndexRoute = AppBusinessesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBusinessesIdRoute,
} as any)
const AppNotebookNotesNoteIdRoute = AppNotebookNotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => AppNotebookRoute,
} as any)
const AppNotebookListsListIdRoute = AppNotebookListsListIdRouteImport.update({
  id: '/lists/$listId',
  path: '/lists/$listId',
  getParentRoute: () => AppNotebookRoute,
} as any)
const AppBusinessesIdTasksRoute = AppBusinessesIdTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppBusinessesIdRoute,
} as any)
const AppBusinessesIdProfitRoute = AppBusinessesIdProfitRouteImport.update({
  id: '/profit',
  path: '/profit',
  getParentRoute: () => AppBusinessesIdRoute,
} as any)
const AppBusinessesIdPeopleRoute = AppBusinessesIdPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppBusinessesIdRoute,
} as any)
const AppBusinessesIdMoneyRoute = AppBusinessesIdMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AppBusinessesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AppChatRouteWithChildren
  '/notebook': typeof AppNotebookRouteWithChildren
  '/personal': typeof AppPersonalRouteWithChildren
  '/admin/users': typeof AppAdminUsersRoute
  '/businesses/$id': typeof AppBusinessesIdRouteWithChildren
  '/chat/$conversationId': typeof AppChatConversationIdRoute
  '/chat/new': typeof AppChatNewRoute
  '/my/tasks': typeof AppMyTasksRoute
  '/notebook/today': typeof AppNotebookTodayRoute
  '/personal/$id': typeof AppPersonalIdRoute
  '/chat/': typeof AppChatIndexRoute
  '/notebook/': typeof AppNotebookIndexRoute
  '/personal/': typeof AppPersonalIndexRoute
  '/businesses/$id/money': typeof AppBusinessesIdMoneyRoute
  '/businesses/$id/people': typeof AppBusinessesIdPeopleRoute
  '/businesses/$id/profit': typeof AppBusinessesIdProfitRoute
  '/businesses/$id/tasks': typeof AppBusinessesIdTasksRoute
  '/notebook/lists/$listId': typeof AppNotebookListsListIdRoute
  '/notebook/notes/$noteId': typeof AppNotebookNotesNoteIdRoute
  '/businesses/$id/': typeof AppBusinessesIdIndexRoute
  '/notebook/lists/': typeof AppNotebookListsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof AppIndexRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/chat/$conversationId': typeof AppChatConversationIdRoute
  '/chat/new': typeof AppChatNewRoute
  '/my/tasks': typeof AppMyTasksRoute
  '/notebook/today': typeof AppNotebookTodayRoute
  '/personal/$id': typeof AppPersonalIdRoute
  '/chat': typeof AppChatIndexRoute
  '/notebook': typeof AppNotebookIndexRoute
  '/personal': typeof AppPersonalIndexRoute
  '/businesses/$id/money': typeof AppBusinessesIdMoneyRoute
  '/businesses/$id/people': typeof AppBusinessesIdPeopleRoute
  '/businesses/$id/profit': typeof AppBusinessesIdProfitRoute
  '/businesses/$id/tasks': typeof AppBusinessesIdTasksRoute
  '/notebook/lists/$listId': typeof AppNotebookListsListIdRoute
  '/notebook/notes/$noteId': typeof AppNotebookNotesNoteIdRoute
  '/businesses/$id': typeof AppBusinessesIdIndexRoute
  '/notebook/lists': typeof AppNotebookListsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/chat': typeof AppChatRouteWithChildren
  '/_app/notebook': typeof AppNotebookRouteWithChildren
  '/_app/personal': typeof AppPersonalRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/businesses/$id': typeof AppBusinessesIdRouteWithChildren
  '/_app/chat/$conversationId': typeof AppChatConversationIdRoute
  '/_app/chat/new': typeof AppChatNewRoute
  '/_app/my/tasks': typeof AppMyTasksRoute
  '/_app/notebook/today': typeof AppNotebookTodayRoute
  '/_app/personal/$id': typeof AppPersonalIdRoute
  '/_app/chat/': typeof AppChatIndexRoute
  '/_app/notebook/': typeof AppNotebookIndexRoute
  '/_app/personal/': typeof AppPersonalIndexRoute
  '/_app/businesses/$id/money': typeof AppBusinessesIdMoneyRoute
  '/_app/businesses/$id/people': typeof AppBusinessesIdPeopleRoute
  '/_app/businesses/$id/profit': typeof AppBusinessesIdProfitRoute
  '/_app/businesses/$id/tasks': typeof AppBusinessesIdTasksRoute
  '/_app/notebook/lists/$listId': typeof AppNotebookListsListIdRoute
  '/_app/notebook/notes/$noteId': typeof AppNotebookNotesNoteIdRoute
  '/_app/businesses/$id/': typeof AppBusinessesIdIndexRoute
  '/_app/notebook/lists/': typeof AppNotebookListsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/notebook'
    | '/personal'
    | '/admin/users'
    | '/businesses/$id'
    | '/chat/$conversationId'
    | '/chat/new'
    | '/my/tasks'
    | '/notebook/today'
    | '/personal/$id'
    | '/chat/'
    | '/notebook/'
    | '/personal/'
    | '/businesses/$id/money'
    | '/businesses/$id/people'
    | '/businesses/$id/profit'
    | '/businesses/$id/tasks'
    | '/notebook/lists/$listId'
    | '/notebook/notes/$noteId'
    | '/businesses/$id/'
    | '/notebook/lists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/admin/users'
    | '/chat/$conversationId'
    | '/chat/new'
    | '/my/tasks'
    | '/notebook/today'
    | '/personal/$id'
    | '/chat'
    | '/notebook'
    | '/personal'
    | '/businesses/$id/money'
    | '/businesses/$id/people'
    | '/businesses/$id/profit'
    | '/businesses/$id/tasks'
    | '/notebook/lists/$listId'
    | '/notebook/notes/$noteId'
    | '/businesses/$id'
    | '/notebook/lists'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/chat'
    | '/_app/notebook'
    | '/_app/personal'
    | '/_app/'
    | '/_app/admin/users'
    | '/_app/businesses/$id'
    | '/_app/chat/$conversationId'
    | '/_app/chat/new'
    | '/_app/my/tasks'
    | '/_app/notebook/today'
    | '/_app/personal/$id'
    | '/_app/chat/'
    | '/_app/notebook/'
    | '/_app/personal/'
    | '/_app/businesses/$id/money'
    | '/_app/businesses/$id/people'
    | '/_app/businesses/$id/profit'
    | '/_app/businesses/$id/tasks'
    | '/_app/notebook/lists/$listId'
    | '/_app/notebook/notes/$noteId'
    | '/_app/businesses/$id/'
    | '/_app/notebook/lists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/personal': {
      id: '/_app/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof AppPersonalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notebook': {
      id: '/_app/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof AppNotebookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/personal/': {
      id: '/_app/personal/'
      path: '/'
      fullPath: '/personal/'
      preLoaderRoute: typeof AppPersonalIndexRouteImport
      parentRoute: typeof AppPersonalRoute
    }
    '/_app/notebook/': {
      id: '/_app/notebook/'
      path: '/'
      fullPath: '/notebook/'
      preLoaderRoute: typeof AppNotebookIndexRouteImport
      parentRoute: typeof AppNotebookRoute
    }
    '/_app/chat/': {
      id: '/_app/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppChatRoute
    }
    '/_app/personal/$id': {
      id: '/_app/personal/$id'
      path: '/$id'
      fullPath: '/personal/$id'
      preLoaderRoute: typeof AppPersonalIdRouteImport
      parentRoute: typeof AppPersonalRoute
    }
    '/_app/notebook/today': {
      id: '/_app/notebook/today'
      path: '/today'
      fullPath: '/notebook/today'
      preLoaderRoute: typeof AppNotebookTodayRouteImport
      parentRoute: typeof AppNotebookRoute
    }
    '/_app/my/tasks': {
      id: '/_app/my/tasks'
      path: '/my/tasks'
      fullPath: '/my/tasks'
      preLoaderRoute: typeof AppMyTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/new': {
      id: '/_app/chat/new'
      path: '/new'
      fullPath: '/chat/new'
      preLoaderRoute: typeof AppChatNewRouteImport
      parentRoute: typeof AppChatRoute
    }
    '/_app/chat/$conversationId': {
      id: '/_app/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof AppChatConversationIdRouteImport
      parentRoute: typeof AppChatRoute
    }
    '/_app/businesses/$id': {
      id: '/_app/businesses/$id'
      path: '/businesses/$id'
      fullPath: '/businesses/$id'
      preLoaderRoute: typeof AppBusinessesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notebook/lists/': {
      id: '/_app/notebook/lists/'
      path: '/lists'
      fullPath: '/notebook/lists/'
      preLoaderRoute: typeof AppNotebookListsIndexRouteImport
      parentRoute: typeof AppNotebookRoute
    }
    '/_app/businesses/$id/': {
      id: '/_app/businesses/$id/'
      path: '/'
      fullPath: '/businesses/$id/'
      preLoaderRoute: typeof AppBusinessesIdIndexRouteImport
      parentRoute: typeof AppBusinessesIdRoute
    }
    '/_app/notebook/notes/$noteId': {
      id: '/_app/notebook/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notebook/notes/$noteId'
      preLoaderRoute: typeof AppNotebookNotesNoteIdRouteImport
      parentRoute: typeof AppNotebookRoute
    }
    '/_app/notebook/lists/$listId': {
      id: '/_app/notebook/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/notebook/lists/$listId'
      preLoaderRoute: typeof AppNotebookListsListIdRouteImport
      parentRoute: typeof AppNotebookRoute
    }
    '/_app/businesses/$id/tasks': {
      id: '/_app/businesses/$id/tasks'
      path: '/tasks'
      fullPath: '/businesses/$id/tasks'
      preLoaderRoute: typeof AppBusinessesIdTasksRouteImport
      parentRoute: typeof AppBusinessesIdRoute
    }
    '/_app/businesses/$id/profit': {
      id: '/_app/businesses/$id/profit'
      path: '/profit'
      fullPath: '/businesses/$id/profit'
      preLoaderRoute: typeof AppBusinessesIdProfitRouteImport
      parentRoute: typeof AppBusinessesIdRoute
    }
    '/_app/businesses/$id/people': {
      id: '/_app/businesses/$id/people'
      path: '/people'
      fullPath: '/businesses/$id/people'
      preLoaderRoute: typeof AppBusinessesIdPeopleRouteImport
      parentRoute: typeof AppBusinessesIdRoute
    }
    '/_app/businesses/$id/money': {
      id: '/_app/businesses/$id/money'
      path: '/money'
      fullPath: '/businesses/$id/money'
      preLoaderRoute: typeof AppBusinessesIdMoneyRouteImport
      parentRoute: typeof AppBusinessesIdRoute
    }
  }
}

interface AppChatRouteChildren {
  AppChatConversationIdRoute: typeof AppChatConversationIdRoute
  AppChatNewRoute: typeof AppChatNewRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
}

const AppChatRouteChildren: AppChatRouteChildren = {
  AppChatConversationIdRoute: AppChatConversationIdRoute,
  AppChatNewRoute: AppChatNewRoute,
  AppChatIndexRoute: AppChatIndexRoute,
}

const AppChatRouteWithChildren =
  AppChatRoute._addFileChildren(AppChatRouteChildren)

interface AppNotebookRouteChildren {
  AppNotebookTodayRoute: typeof AppNotebookTodayRoute
  AppNotebookIndexRoute: typeof AppNotebookIndexRoute
  AppNotebookListsListIdRoute: typeof AppNotebookListsListIdRoute
  AppNotebookNotesNoteIdRoute: typeof AppNotebookNotesNoteIdRoute
  AppNotebookListsIndexRoute: typeof AppNotebookListsIndexRoute
}

const AppNotebookRouteChildren: AppNotebookRouteChildren = {
  AppNotebookTodayRoute: AppNotebookTodayRoute,
  AppNotebookIndexRoute: AppNotebookIndexRoute,
  AppNotebookListsListIdRoute: AppNotebookListsListIdRoute,
  AppNotebookNotesNoteIdRoute: AppNotebookNotesNoteIdRoute,
  AppNotebookListsIndexRoute: AppNotebookListsIndexRoute,
}

const AppNotebookRouteWithChildren = AppNotebookRoute._addFileChildren(
  AppNotebookRouteChildren,
)

interface AppPersonalRouteChildren {
  AppPersonalIdRoute: typeof AppPersonalIdRoute
  AppPersonalIndexRoute: typeof AppPersonalIndexRoute
}

const AppPersonalRouteChildren: AppPersonalRouteChildren = {
  AppPersonalIdRoute: AppPersonalIdRoute,
  AppPersonalIndexRoute: AppPersonalIndexRoute,
}

const AppPersonalRouteWithChildren = AppPersonalRoute._addFileChildren(
  AppPersonalRouteChildren,
)

interface AppBusinessesIdRouteChildren {
  AppBusinessesIdMoneyRoute: typeof AppBusinessesIdMoneyRoute
  AppBusinessesIdPeopleRoute: typeof AppBusinessesIdPeopleRoute
  AppBusinessesIdProfitRoute: typeof AppBusinessesIdProfitRoute
  AppBusinessesIdTasksRoute: typeof AppBusinessesIdTasksRoute
  AppBusinessesIdIndexRoute: typeof AppBusinessesIdIndexRoute
}

const AppBusinessesIdRouteChildren: AppBusinessesIdRouteChildren = {
  AppBusinessesIdMoneyRoute: AppBusinessesIdMoneyRoute,
  AppBusinessesIdPeopleRoute: AppBusinessesIdPeopleRoute,
  AppBusinessesIdProfitRoute: AppBusinessesIdProfitRoute,
  AppBusinessesIdTasksRoute: AppBusinessesIdTasksRoute,
  AppBusinessesIdIndexRoute: AppBusinessesIdIndexRoute,
}

const AppBusinessesIdRouteWithChildren = AppBusinessesIdRoute._addFileChildren(
  AppBusinessesIdRouteChildren,
)

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRouteWithChildren
  AppNotebookRoute: typeof AppNotebookRouteWithChildren
  AppPersonalRoute: typeof AppPersonalRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppBusinessesIdRoute: typeof AppBusinessesIdRouteWithChildren
  AppMyTasksRoute: typeof AppMyTasksRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRouteWithChildren,
  AppNotebookRoute: AppNotebookRouteWithChildren,
  AppPersonalRoute: AppPersonalRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppBusinessesIdRoute: AppBusinessesIdRouteWithChildren,
  AppMyTasksRoute: AppMyTasksRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
